# Generated by Django 5.0.6 on 2024-07-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_access_control', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
