# Generated by Django 5.0.6 on 2024-07-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_employee_bank_account_number_employee_bank_name'),
        ('salary_processing', '0002_alter_salaryrecord_allowances_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('employee', 'month')},
        ),
    ]
