# Generated by Django 5.0.6 on 2024-07-03 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='description',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
        migrations.AddField(
            model_name='report',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 3, 11, 31, 21, 919160, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='net_salaries',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(default=datetime.datetime(2024, 7, 3, 11, 35, 37, 578041, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 3, 11, 47, 29, 3373, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='total_salaries',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
