# Generated by Django 5.0.6 on 2024-07-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_employee_bank_account_number_employee_bank_name'),
        ('reporting', '0002_remove_report_created_at_remove_report_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='employees',
            field=models.ManyToManyField(to='employee_management.employee'),
        ),
    ]
